version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
      - "Github actions dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    target-branch: "dev"
    labels:
      - "pip dependencies"
    allow:
      - dependency-type: direct
      - dependency-type: indirect