[tool.black]
line-length = 120
skip-string-normalization = true
required-version = "23.1.0"
extend-exclude = "/(slides)/"

[tool.pytest.ini_options]
addopts = "--cov ./deepparse --cov-report html --cov-report xml --cov-config=.coveragerc"

testpaths = [
    "tests",
]

[tool.pylint.ini_options]
DJANGO_SETTINGS_MODULE = "settings"
